title: Karan Mirani's Blog
email: blog@mirani.ca
description: My ever evolving understanding of how things work
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mirani.ca"

# Build settings
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
